Update generator-macos.yml

diff --git a/.github/workflows/generator-macos.yml b/.github/workflows/generator-macos.yml
--- a/.github/workflows/generator-macos.yml
+++ b/.github/workflows/generator-macos.yml
@@ -49,46 +49,21 @@ env:
   STATUS_URL: "${{ secrets.GENURL }}/updategh"
   SLOGAN: "${{ fromJson(inputs.extras).slogan }}"
 
-jobs:
-  generate-bridge:
-    uses: ./.github/workflows/bridge.yml
-    with:
-      version: ${{ fromJson(inputs.extras).version }}
-
-  build-macos:
-    needs: generate-bridge
-    runs-on: ${{ matrix.job.os }}
+build-for-macOS-arm64-selfhost:
+    # use build-for-macOS instead
+    if: false
+    runs-on: [self-hosted, macOS, ARM64]
+    needs: [generate-bridge]
     steps:
-      - name: Update build status
-        continue-on-error: true
-        run: |
-          curl -X POST ${{ env.STATUS_URL }} \
-          -H "Content-Type: application/json" \
-          -d "{\"uuid\":\"${{ env.UUIDFOLDER }}\",\"status\":\"Starting macOS build...\"}"
-
-      - uses: actions/checkout@v3
+      - name: Export GitHub Actions cache environment variables
+        uses: actions/github-script@v6
         with:
-          repository: 'rustdesk/rustdesk'
-          ref: "${{ env.VERSION }}"
-          submodules: recursive
+          script: |
+            core.exportVariable('ACTIONS_CACHE_URL', process.env.ACTIONS_CACHE_URL || '');
+            core.exportVariable('ACTIONS_RUNTIME_TOKEN', process.env.ACTIONS_RUNTIME_TOKEN || '');
 
-      - name: Install Rust toolchain
-        uses: dtolnay/rust-toolchain@stable
-        with:
-          toolchain: ${{ env.RUST_VERSION }}
-          targets: aarch64-apple-darwin
-
-      - name: Install Flutter
-        uses: subosito/flutter-action@v2.12.0
-        with:
-          channel: "stable"
-          flutter-version: ${{ env.FLUTTER_VERSION }}
-          cache: true
-
-      - name: Install dependencies
-        run: |
-          brew install nasm yasm pkg-config cmake create-dmg ninja
-          cargo install flutter_rust_bridge_codegen --version ${{ env.FLUTTER_RUST_BRIDGE_VERSION }}
+      - name: Checkout source code
+        uses: actions/checkout@v4
 
       - name: Restore bridge files
         uses: actions/download-artifact@master
@@ -96,93 +71,52 @@ jobs:
           name: bridge-artifact
           path: ./
 
-      - name: Update Slogan
-        if: env.SLOGAN != ''
-        run: |
-          find . -type f -name "*.rs" -exec sed -i '' "s|Connecting the world|${{ env.SLOGAN }}|g" {} +
-
-      - name: Setup Flutter project
-        run: |
-          cd src/ui/flutter
-          flutter clean
-          flutter pub get
-          flutter config --enable-macos-desktop
-          cd ../../..
-
-      - name: Fix connection delay
-        if: ${{ fromJson(inputs.extras).delayFix == 'true' }}
-        run: |
-          sed -i '' -e '/if !key.is_empty() && !token.is_empty() {/,/}/d' ./src/client.rs
-
       - name: Build rustdesk
         run: |
-          cd src/ui/flutter
-          flutter build macos --release --no-tree-shake-icons
-          cd ../../..
+          ./build.py --flutter --hwcodec
 
-      - name: Create DMG
+      - name: create unsigned dmg
+        if: env.UPLOAD_ARTIFACT == 'true'
         run: |
           CREATE_DMG="$(command -v create-dmg)"
           CREATE_DMG="$(readlink -f "$CREATE_DMG")"
           sed -i -e 's/MAXIMUM_UNMOUNTING_ATTEMPTS=3/MAXIMUM_UNMOUNTING_ATTEMPTS=7/' "$CREATE_DMG"
-          
-          cd src/ui/flutter/build/macos/Build/Products/Release
-          if [ "${{ inputs.appname }}" != "" ]; then
-            mv "RustDesk.app" "${{ inputs.appname }}.app"
-            APP_NAME="${{ inputs.appname }}"
-          else
-            APP_NAME="RustDesk"
-          fi
-          
-          chmod -R +x "$APP_NAME.app"
-          
-          create-dmg \
-            --volname "$APP_NAME" \
-            --window-size 800 400 \
-            --icon-size 100 \
-            --icon "$APP_NAME.app" 200 190 \
-            --hide-extension "$APP_NAME.app" \
-            --app-drop-link 600 185 \
-            --no-internet-enable \
-            "${{ inputs.filename }}.dmg" \
-            "./$APP_NAME.app"
-            
-          mkdir -p ../../../../../../../../SignOutput/
-          mv "${{ inputs.filename }}.dmg" ../../../../../../../../SignOutput/
+          create-dmg --icon "RustDesk.app" 200 190 --hide-extension "RustDesk.app" --window-size 800 400 --app-drop-link 600 185 rustdesk-${{ env.VERSION }}-arm64.dmg ./flutter/build/macos/Build/Products/Release/RustDesk.app
 
-      - name: Sign DMG
-        if: env.MACOS_P12_BASE64 != ''
-        env:
-          MACOS_P12_BASE64: "${{ secrets.MACOS_P12_BASE64 }}"
-          MACOS_P12_PASSWORD: "${{ secrets.MACOS_P12_PASSWORD }}"
-        run: |
-          echo $MACOS_P12_BASE64 | base64 --decode > certificate.p12
-          security create-keychain -p mysecretpassword build.keychain
-          security default-keychain -s build.keychain
-          security unlock-keychain -p mysecretpassword build.keychain
-          security import certificate.p12 -k build.keychain -P $MACOS_P12_PASSWORD -T /usr/bin/codesign
-          security set-key-partition-list -S apple-tool:,apple:,codesign: -s -k mysecretpassword build.keychain
-          codesign --force --options runtime -s "Developer ID Application" --keychain build.keychain "./SignOutput/${{ inputs.filename }}.dmg" -vvv
-
-      - name: Upload to FTP
-        if: ${{ env.UPLOAD_ARTIFACT == 'true' }}
-        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
+      - name: Upload unsigned macOS app
+        if: env.UPLOAD_ARTIFACT == 'true'
+        uses: actions/upload-artifact@master
         with:
-          server: ${{ secrets.GEN_FTP_SERVER }}
-          username: ${{ secrets.GEN_FTP_USER }}
-          password: ${{ secrets.GEN_FTP_PASSWORD }}
-          local-dir: ./SignOutput/
-          server-dir: exe/${{ env.UUIDFOLDER }}/
+          name: rustdesk-unsigned-macos-arm64
+          path: rustdesk-${{ env.VERSION }}-arm64.dmg # can not upload the directory directly or tar.gz file, which destroy the link structure, causing the codesign failed
 
-      - name: Update build status
-        if: always()
-        continue-on-error: true
+      - name: Codesign app and create signed dmg
+        if: env.MACOS_P12_BASE64 != null && env.UPLOAD_ARTIFACT == 'true'
         run: |
-          if [ ${{ job.status }} == "success" ]; then
-            STATUS="Success"
-          else
-            STATUS="Build failed"
-          fi
-          curl -X POST ${{ env.STATUS_URL }} \
-          -H "Content-Type: application/json" \
-          -d "{\"uuid\":\"${{ env.UUIDFOLDER }}\",\"status\":\"$STATUS\"}"
+          # Patch create-dmg to give more attempts to unmount image
+          CREATE_DMG="$(command -v create-dmg)"
+          CREATE_DMG="$(readlink -f "$CREATE_DMG")"
+          sed -i -e 's/MAXIMUM_UNMOUNTING_ATTEMPTS=3/MAXIMUM_UNMOUNTING_ATTEMPTS=7/' "$CREATE_DMG"
+          # start sign the rustdesk.app and dmg
+          rm -rf *.dmg || true
+          codesign --force --options runtime -s ${{ secrets.MACOS_CODESIGN_IDENTITY }} --deep --strict ./flutter/build/macos/Build/Products/Release/RustDesk.app -vvv
+          create-dmg --icon "RustDesk.app" 200 190 --hide-extension "RustDesk.app" --window-size 800 400 --app-drop-link 600 185 rustdesk-${{ env.VERSION }}.dmg ./flutter/build/macos/Build/Products/Release/RustDesk.app
+          codesign --force --options runtime -s ${{ secrets.MACOS_CODESIGN_IDENTITY }} --deep --strict rustdesk-${{ env.VERSION }}.dmg -vvv
+          # notarize the rustdesk-${{ env.VERSION }}.dmg
+          rcodesign notary-submit --api-key-path ~/.p12/api-key.json  --staple rustdesk-${{ env.VERSION }}.dmg
+
+      - name: Rename rustdesk
+        if: env.UPLOAD_ARTIFACT == 'true'
+        run: |
+          for name in rustdesk*??.dmg; do
+              mv "$name" "${name%%.dmg}-aarch64.dmg"
+          done
+
+      - name: Publish DMG package
+        if: env.UPLOAD_ARTIFACT == 'true'
+        uses: softprops/action-gh-release@v1
+        with:
+          prerelease: true
+          tag_name: ${{ env.TAG_NAME }}
+          files: |
+            rustdesk*-aarch64.dmg
